# fly.toml app configuration file generated for todoslasttry on 2023-11-16T05:27:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "todoslasttry"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
